// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8a5dg9bseiE-oYkCteXGTqvAdF2QR6PA',
    appId: '1:729399796474:web:6aa1997d6be2a703ec9f43',
    messagingSenderId: '729399796474',
    projectId: 'pet-care-b0d24',
    authDomain: 'pet-care-b0d24.firebaseapp.com',
    storageBucket: 'pet-care-b0d24.appspot.com',
    measurementId: 'G-8MCM6FJJ9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf2hHdJu9g0wGccyCVTkcty5w8hn99NbU',
    appId: '1:729399796474:android:ad8afe41c3bd15a1ec9f43',
    messagingSenderId: '729399796474',
    projectId: 'pet-care-b0d24',
    databaseURL: 'https://pet-care-b0d24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pet-care-b0d24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJlBP6NYpNrnLmQoXf-mgrJxLIKckNESE',
    appId: '1:729399796474:ios:858aa763b5d2c653ec9f43',
    messagingSenderId: '729399796474',
    projectId: 'pet-care-b0d24',
    databaseURL: 'https://pet-care-b0d24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pet-care-b0d24.appspot.com',
    androidClientId: '729399796474-ph5cn0efl4mkp7kpvk8uod0pn646f7gn.apps.googleusercontent.com',
    iosClientId: '729399796474-0t5n3dnil1ej6fns407ke8lsvuiu7ied.apps.googleusercontent.com',
    iosBundleId: 'com.nmloc.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJlBP6NYpNrnLmQoXf-mgrJxLIKckNESE',
    appId: '1:729399796474:ios:ac7b19141e9d832dec9f43',
    messagingSenderId: '729399796474',
    projectId: 'pet-care-b0d24',
    storageBucket: 'pet-care-b0d24.appspot.com',
    iosBundleId: 'com.example.petcare',
  );
}